---
name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run stack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell environment
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.4.2'
          cabal-version: '3.8.1.0'
          enable-stack: true
          stack-version: '2.9.1'

      - name: Build solution
        run: stack build

      - name: Run tests
        run: stack test
      
      
